owner: scout-io
repo: scout
charts-repo-url: https://github.com/scout-io/scout/releases/download
charts-dir: charts
pages-branch: main
# Add configuration for chart-releaser to update index.yaml
index-path: index.yaml
packages-with-index: true
# Configure GitHub Pages deployment
pages-index-path: index.yaml
