apiVersion: v1
kind: Secret
metadata:
  name: scout-secrets
  namespace: scout
  labels:
    app.kubernetes.io/name: scout
    app.kubernetes.io/component: config
type: Opaque
data:
  # Base64 encoded values - replace with actual values
  # To generate: echo -n "your-secure-token" | base64
  SCOUT_AUTH_TOKEN: "" # Empty by default, set during deployment
stringData:
  # Use stringData for easier management - these will be base64 encoded automatically
  SCOUT_PROTECTED_API: "false"
