{{- if .Values.prometheus.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "scout.fullname" . }}-prometheus-config
  namespace: {{ include "scout.namespace" . }}
  labels:
    {{- include "scout.labels" . | nindent 4 }}
    app.kubernetes.io/component: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: {{ .Values.prometheus.config.scrapeInterval }}
      evaluation_interval: {{ .Values.prometheus.config.evaluationInterval }}

    scrape_configs:
      - job_name: 'scout-backend'
        kubernetes_sd_configs:
        - role: endpoints
          namespaces:
            names:
            - {{ include "scout.namespace" . }}
        relabel_configs:
        # Only scrape services with the prometheus.io/scrape annotation
        - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape]
          action: keep
          regex: true
        # Use the prometheus.io/path annotation to specify the metrics path
        - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_path]
          action: replace
          target_label: __metrics_path__
          regex: (.+)
        # Use the prometheus.io/port annotation to specify the port
        - source_labels: [__address__, __meta_kubernetes_service_annotation_prometheus_io_port]
          action: replace
          regex: ([^:]+)(?::\d+)?;(\d+)
          replacement: $1:$2
          target_label: __address__
        # Add service name as a label
        - source_labels: [__meta_kubernetes_service_name]
          action: replace
          target_label: service
        # Add namespace as a label
        - source_labels: [__meta_kubernetes_namespace]
          action: replace
          target_label: namespace

      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
        - role: pod
          namespaces:
            names:
            - {{ include "scout.namespace" . }}
        relabel_configs:
        # Only scrape pods with the prometheus.io/scrape annotation
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
          action: keep
          regex: true
        # Use the prometheus.io/path annotation to specify the metrics path
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
          action: replace
          target_label: __metrics_path__
          regex: (.+)
        # Use the prometheus.io/port annotation to specify the port
        - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
          action: replace
          regex: ([^:]+)(?::\d+)?;(\d+)
          replacement: $1:$2
          target_label: __address__
        # Add pod name as a label
        - source_labels: [__meta_kubernetes_pod_name]
          action: replace
          target_label: pod
        # Add namespace as a label
        - source_labels: [__meta_kubernetes_namespace]
          action: replace
          target_label: namespace
{{- end }} 