{{- if .Values.redis.enabled }}
{{- if .Values.redis.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "scout.fullname" . }}-redis-data
  namespace: {{ include "scout.namespace" . }}
  labels:
    {{- include "scout.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.redis.persistence.storageClass }}
  storageClassName: {{ .Values.redis.persistence.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.redis.persistence.size }}
---
{{- end }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "scout.fullname" . }}-redis
  namespace: {{ include "scout.namespace" . }}
  labels:
    {{- include "scout.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  replicas: {{ .Values.redis.replicas }}
  selector:
    matchLabels:
      {{- include "scout.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: redis
  template:
    metadata:
      labels:
        {{- include "scout.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: redis
    spec:
      containers:
      - name: redis
        image: {{ include "scout.image" (dict "repository" .Values.images.redis.repository "tag" .Values.images.redis.tag) }}
        ports:
        - containerPort: {{ .Values.service.ports.redis }}
          name: redis
        command:
        - redis-server
        - --save
        - {{ .Values.redis.config.saveInterval | quote }}
        - {{ .Values.redis.config.saveChanges | quote }}
        - --appendonly
        - {{ .Values.redis.config.appendOnly | quote }}
        - --appendfsync
        - {{ .Values.redis.config.appendFsync | quote }}
        {{- if .Values.redis.persistence.enabled }}
        volumeMounts:
        - name: redis-data
          mountPath: /data
        {{- end }}
        resources:
          {{- toYaml .Values.redis.resources | nindent 10 }}
        livenessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 5
          periodSeconds: 5
      {{- if .Values.redis.persistence.enabled }}
      volumes:
      - name: redis-data
        persistentVolumeClaim:
          claimName: {{ include "scout.fullname" . }}-redis-data
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "scout.redis.serviceName" . }}
  namespace: {{ include "scout.namespace" . }}
  labels:
    {{- include "scout.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  ports:
  - port: {{ .Values.service.ports.redis }}
    targetPort: {{ .Values.service.ports.redis }}
    name: redis
  selector:
    {{- include "scout.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: redis
{{- end }} 