{{- if .Values.frontend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "scout.fullname" . }}-frontend
  namespace: {{ include "scout.namespace" . }}
  labels:
    {{- include "scout.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      {{- include "scout.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: frontend
  template:
    metadata:
      labels:
        {{- include "scout.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: frontend
    spec:
      {{- if .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.global.imagePullSecrets | nindent 8 }}
      {{- end }}
      {{- if .Values.global.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.global.nodeSelector | nindent 8 }}
      {{- end }}
      containers:
      - name: frontend
        image: {{ include "scout.image" (dict "repository" .Values.images.frontend.repository "tag" .Values.images.frontend.tag) }}
        imagePullPolicy: {{ .Values.images.frontend.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.ports.frontend }}
          name: http
        resources:
          {{- toYaml .Values.frontend.resources | nindent 10 }}
        livenessProbe:
          httpGet:
            path: /
            port: {{ .Values.service.ports.frontend }}
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: {{ .Values.service.ports.frontend }}
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "scout.frontend.serviceName" . }}
  namespace: {{ include "scout.namespace" . }}
  labels:
    {{- include "scout.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  ports:
  - port: {{ .Values.service.ports.frontend }}
    targetPort: {{ .Values.service.ports.frontend }}
    name: http
  selector:
    {{- include "scout.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
{{- end }} 