{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "scout.fullname" . }}-network-policy
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "scout.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "scout.name" . }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  # Allow frontend to backend
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/component: frontend
    ports:
    - protocol: TCP
      port: 8000
  # Allow nginx to frontend and backend
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/component: nginx
    ports:
    - protocol: TCP
      port: 3000
    - protocol: TCP
      port: 8000
  # Allow Prometheus scraping
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/component: prometheus
    ports:
    - protocol: TCP
      port: 8000
  # Allow external access to nginx (if enabled)
  {{- if .Values.networkPolicy.allowExternalAccess }}
  - ports:
    - protocol: TCP
      port: 80
  {{- end }}
  egress:
  # Allow backend to Redis
  - to:
    - podSelector:
        matchLabels:
          app.kubernetes.io/component: redis
    ports:
    - protocol: TCP
      port: 6379
  # Allow DNS resolution
  - to: []
    ports:
    - protocol: UDP
      port: 53
  # Allow Prometheus to scrape metrics
  - to:
    - podSelector:
        matchLabels:
          app.kubernetes.io/component: backend
    ports:
    - protocol: TCP
      port: 8000
{{- end }} 