apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "scout.nginx.fullname" . }}-config
  labels:
    {{- include "scout.labels" . | nindent 4 }}
data:
  default.conf: |
    upstream backend_servers {
        server {{ include "scout.backend.fullname" . }}:8000;
    }

    upstream frontend_servers {
        server {{ include "scout.frontend.fullname" . }}:3000;
    }

    server {
        listen 80;
        server_name _;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        location / {
            proxy_pass http://frontend_servers;
        }

        location /api {
            proxy_pass http://backend_servers/api;
            proxy_http_version 1.1;
            proxy_set_header Connection "";
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /logs/stream {
            proxy_pass http://backend_servers/logs/stream;
            proxy_http_version 1.1;
            proxy_set_header Connection "";
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /admin {
            proxy_pass http://backend_servers/admin;
            proxy_http_version 1.1;
            proxy_set_header Connection "";
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /openapi {
            proxy_pass http://backend_servers/openapi.json;
        }

        location /docs {
            proxy_pass http://backend_servers/docs;
            proxy_http_version 1.1;
            proxy_set_header Connection "";
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /nginx-health {
            access_log off;
            return 200 "healthy\n";
            add_header Content-Type text/plain;
        }
    }

