apiVersion: v1
kind: Secret
metadata:
  name: {{ include "scout.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "scout.labels" . | nindent 4 }}
type: Opaque
data:
  # Base64 encoded values
  {{- if .Values.auth.protectedAPI }}
  SCOUT_PROTECTED_API: {{ .Values.auth.protectedAPI | toString | b64enc }}
  {{- end }}
  {{- if .Values.auth.token }}
  SCOUT_AUTH_TOKEN: {{ .Values.auth.token | b64enc }}
  {{- end }}
  {{- if .Values.redis.password }}
  REDIS_PASSWORD: {{ .Values.redis.password | b64enc }}
  {{- end }}
  {{- if .Values.auth.tokenExpiration }}
  SCOUT_TOKEN_EXPIRATION: {{ .Values.auth.tokenExpiration | toString | b64enc }}
  {{- end }}
---
{{- if .Values.redis.authEnabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "scout.fullname" . }}-redis-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "scout.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.redis.password }}
  redis-password: {{ .Values.redis.password | b64enc }}
  {{- else }}
  redis-password: {{ "scout-redis-password" | b64enc }}
  {{- end }}
{{- end }} 