{{- if .Values.rbac.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "scout.fullname" . }}-backend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "scout.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "scout.fullname" . }}-backend-role
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "scout.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
{{- if .Values.rbac.minimalPermissions }}
# Minimal permissions for basic operation
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get", "list", "watch"]
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "scout.fullname" . }}-backend-binding
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "scout.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "scout.fullname" . }}-backend-role
subjects:
- kind: ServiceAccount
  name: {{ include "scout.fullname" . }}-backend
  namespace: {{ .Release.Namespace }}
{{- end }} 